name: Globalization
on: push
    
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
      - name: G11n Radar
        uses: citrix-workspace/g11n-scan@bugfix_2
        with:
          repoToken: ${{secrets.GITHUB_TOKEN}}
          skip: 'bundles/coming_soon/'
      - name: Slack Notification
        uses: archive/github-actions-slack@v1.0.0
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACKBOT_TOKEN }}
          slack-channel: test_boz
          slack-text: Hello! Event "${{ github.event_name }}" in "${{ github.repository }}"
          slack-optional-icon_emoji: ":fire:"
          slack-optional-as_user: false
